version: "3.4"

services:
  postgres:
    image: postgres:10-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: books
    networks:
      - app

  postgres_tests:
    image: postgres:10-alpine
    container_name: test-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: test-books
    ports:
      - 5433:5433
    command: -p 5433

networks:
  app:
